Repository codeit-part2-project/open-mind, pull requests merged in 2024-12, with the labels that each got.

#2 Epic/api 함수 구현
  src/api/answers.js
  src/api/questions.js
  src/api/subjects.js
Labels: Priority: High 🔥, Type: Epic :rocket:

#3 Feat/modal 컴포넌트 레이아웃 구현
  package-lock.json
  package.json
  public/index.html
  src/components/App.jsx
  src/components/Context/index.jsx
  src/components/Modals/index.jsx
  src/utils/portal/index.jsx
  src/utils/portal/portal.jsx
  tailwind.config.js
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#4 Feat/modal form제출 구현
  src/components/Context/index.jsx
  src/components/Modals/index.jsx
Labels: Priority: Medium :bookmark:, Type: Bug :bug:, Type: Feature :sparkles:

#5 Feat/리스트페이지 레이아웃
  src/components/CardList.jsx
  src/pages/QuestionList/index.jsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#6 Feat/main 화면 레이아웃 구현
  src/assets/images/icons/ic_Person.svg
  src/assets/images/img_Banner.svg
  src/pages/Home/index.jsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#7 Feat/헤더 레이아웃
  src/components/feedHeader/index.jsx
  src/pages/Answer/index.jsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#8 Feat/main form제출 구현
  src/pages/Home/index.jsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#9 Feat/헤더 레이아웃
  src/assets/images/img_Header.svg
  src/components/feedHeader/index.jsx
Labels: Priority: Low 🐢, Type: Feature :sparkles:

#10 Feat/Pagination 기능 구현
  package-lock.json
  package.json
  src/components/Pagination/index.jsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#12 Feat/pagination style 구현
  src/components/Pagination/index.jsx
Labels: Priority: Low 🐢, Type: Feature :sparkles:, Type: Improve UX :arrow_up:

#17 Feat/답변 상태 표시
  package-lock.json
  package.json
  src/components/AnswerStatus/index.jsx
Labels: Priority: Low 🐢, Type: Feature :sparkles:

#16 Feat/좋아요 싫어요 기능
  package-lock.json
  package.json
  src/assets/images/icons/thumbs-down.svg
  src/assets/images/icons/thumbs-up.svg
  src/components/Feed/favorite/index.jsx
  src/components/Feed/index.jsx
  src/pages/Feed/index.jsx
Labels: Priority: Low 🐢, Type: Feature :sparkles:, Type: Improve UX :arrow_up:

#25 Feat/질문 개수 표시
  .github/workflows/ci.yaml
  netlify.toml
  src/components/CountQuestion/index.jsx
Labels: Priority: Low 🐢, Type: Feature :sparkles:

#32 Epic/main 화면 구현
  src/assets/images/icons/ic_Person.svg
  src/assets/images/img_Banner.svg
  src/pages/Home/index.jsx
Labels: Priority: High 🔥, Type: Merge :truck:

#31 Feat/좋아요 싫어요 기능
  .github/workflows/ci.yaml
  netlify.toml
  src/components/Feed/favorite/index.jsx
  src/pages/Feed/index.jsx
Labels: Priority: Low 🐢, Type: Feature :sparkles:

#33 Feat/QnA 리스트 구현
  src/assets/images/img_QuestionBox.svg
  src/components/AnswerContent/index.jsx
  src/components/QnAList/index.jsx
  src/pages/Answer/index.jsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#35 Feat/pagination 연동
  src/assets/images/icons/ic_Arrow-down.svg
  src/assets/styles/index.scss
  src/components/CardList/index.jsx
  src/components/Pagination/index.jsx
  src/components/SortDropDown/index.jsx
  src/pages/QuestionList/index.jsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#38 Feat/리스트페이지 페이지이동 기능
  src/components/CardList/index.jsx
  src/pages/QuestionList/index.jsx
Labels: Priority: High 🔥, Type: Feature :sparkles:

#37 Feat/무한스크롤 구현
  src/pages/Feed/index.jsx
Labels: Priority: Low 🐢, Type: Feature :sparkles:

#40 Feat/modal 연동
  public/index.html
  src/components/App.jsx
  src/components/Context/index.jsx
  src/components/Feed/favorite/index.jsx
  src/components/Modals/index.jsx
  src/pages/Feed/index.jsx
  src/utils/portal/index.jsx
  src/utils/portal/portal.jsx
  tailwind.config.js
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#42 Feat/QnA 리스트 스타일링
  package-lock.json
  package.json
  src/assets/images/icons/Messages.svg
  src/assets/images/icons/ic_Messages.svg
  src/assets/images/icons/thumbs-down.svg
  src/assets/images/icons/thumbs-up.svg
  src/assets/images/img_QusetionBox.svg
  src/components/AnswerContent/index.jsx
  src/components/AnswerStatus/index.jsx
  src/components/CountFavorite/index.jsx
  src/components/CountQuestion/index.jsx
  src/components/QnAList/index.jsx
  src/components/QuestionContent/index.jsx
  src/pages/Answer/index.jsx
  src/pages/Feed/index.jsx
  src/utils/dateUtils.js
  tailwind.config.js
Labels: Priority: Low 🐢, Type: Feature :sparkles:

#43 Refactor/list-page
  public/index.html
  src/components/CardList/index.jsx
  src/components/Pagination/index.jsx
  src/components/SortDropDown/index.jsx
  src/pages/QuestionList/index.jsx
  tailwind.config.js
Labels: Priority: Low 🐢, Type: Improve UX :arrow_up:, Type: Refactor :recycle:

#44 Feat/modal 외부 스크롤 방지
  src/components/Context/index.jsx
  src/components/Feed/favorite/index.jsx
  src/components/Modals/index.jsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#45 Epic/list page -> merge 브랜치 병합
  package-lock.json
  package.json
  public/index.html
  src/assets/images/icons/ic_Arrow-down.svg
  src/assets/images/icons/ic_Arrow-left.svg
  src/assets/images/icons/ic_Arrow-right.svg
  src/assets/images/icons/ic_Messages.svg
  src/components/CardList/index.jsx
  src/components/Pagination/index.jsx
  src/components/SortDropDown/index.jsx
  src/hooks/useViewport/index.jsx
  src/pages/QuestionList/index.jsx
  tailwind.config.js
Labels: Priority: High 🔥, Type: Bug :bug:, Type: Merge :truck:

#47 Feat/feed페이지 공용컴포넌트 적용
  package-lock.json
  package.json
  src/assets/images/icons/ic_Messages.svg
  src/assets/images/icons/ic_Person.svg
  src/assets/images/img_Banner.svg
  src/assets/images/img_Header.svg
  src/assets/images/img_QuestionBox.svg
  src/components/AnswerContent/index.jsx
  src/components/AnswerStatus/index.jsx
  src/components/Context/index.jsx
  src/components/CountFavorite/index.jsx
  src/components/CountQuestion/index.jsx
  src/components/DeleteIdBtn/index.jsx
  src/components/Header/index.jsx
  src/components/Modals/index.jsx
  src/components/QnAList/index.jsx
  src/components/QuestionContent/index.jsx
  src/components/ToastDeleteId/index.jsx
  src/pages/Answer/index.jsx
  src/pages/Feed/index.jsx
  src/pages/Home/index.jsx
  src/utils/dateUtils.js
  tailwind.config.js
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:, Type: Refactor :recycle:

#48 Refactor/좋아요 기능 개선
  src/components/CountFavorite/index.jsx
  src/components/QnAList/index.jsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:, Type: Refactor :recycle:

#50 Feat/공유하기 기능 구현
  public/index.html
  src/components/Header/index.jsx
  src/hooks/customHooks.jsx
  src/hooks/useFacebookShare/index.jsx
  src/hooks/useKakaoShare/index.jsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#51 Feat/케밥 구현
  src/assets/images/icons/ic_Close.svg
  src/assets/images/icons/ic_Edit.svg
  src/assets/images/icons/ic_Rejection.svg
  src/components/AnswerStatus/index.jsx
  src/components/DeleteIdBtn/index.jsx
  src/components/Header/index.jsx
  src/components/Kebab/index.jsx
  src/components/QnAList/index.jsx
  src/pages/Answer/index.jsx
  tailwind.config.js
Labels: Priority: Low 🐢, Type: Feature :sparkles:

#53 Feat/케밥 질문삭제 구현
  src/components/Kebab/index.jsx
  src/components/QnAList/index.jsx
  src/components/QuestionDelete/index.jsx
  src/pages/Answer/index.jsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#49 Feat/answer 무한스크롤 구현
  src/components/QnAList/index.jsx
  src/index.jsx
  src/pages/Answer/index.jsx
  src/pages/Home/index.jsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:, Type: Refactor :recycle:

#52 Refactor/feed 스타일 개선
  public/index.html
  src/components/AnswerContent/index.jsx
  src/components/AnswerStatus/index.jsx
  src/components/Context/index.jsx
  src/components/CountQuestion/index.jsx
  src/components/Header/index.jsx
  src/components/Modals/index.jsx
  src/components/QuestionContent/index.jsx
  src/pages/Feed/index.jsx
  tailwind.config.js
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#54 Fix/feed redirection
  src/pages/Feed/index.jsx
Labels: Priority: High 🔥, Type: Bug :bug:

#56 Feat/케밥 답변삭제 구현
  src/components/AnswerContent/index.jsx
  src/components/AnswerDelete/index.jsx
  src/components/AnswerStatus/index.jsx
  src/components/Kebab/index.jsx
  src/components/QnAList/index.jsx
  src/pages/Answer/index.jsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#58 Feat/케밥 답변거절 구현
  src/components/AnswerContent/index.jsx
  src/components/AnswerRejection/index.jsx
  src/components/Kebab/index.jsx
  src/components/QnAList/index.jsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#57 Refactor/list page 애니메이션
  src/components/CardList/index.jsx
  src/components/SortDropDown/index.jsx
  src/pages/QuestionList/index.jsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#59 :sparkles: feat : 케밥 답변수정 구현
  src/components/AnswerEdit/index.jsx
  src/components/AnswerEditForm/index.jsx
  src/components/Kebab/index.jsx
  src/components/QnAList/index.jsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#55 Epic/feed 화면 구현 -> merge 브랜치 병합
  package-lock.json
  package.json
  public/index.html
  src/assets/images/icons/Messages.svg
  src/assets/images/icons/thumbs-down.svg
  src/assets/images/icons/thumbs-up.svg
  src/assets/images/img_Header.svg
  src/assets/images/img_QuestionBox.svg
  src/assets/images/img_QusetionBox.svg
  src/components/AnswerContent/index.jsx
  src/components/AnswerStatus/index.jsx
  src/components/App.jsx
  src/components/Context/index.jsx
  src/components/CountFavorite/index.jsx
  src/components/CountQuestion/index.jsx
  src/components/DeleteIdBtn/index.jsx
  src/components/Header/index.jsx
  src/components/Modals/index.jsx
  src/components/QnAList/index.jsx
  src/components/QuestionContent/index.jsx
  src/components/ToastDeleteId/index.jsx
  src/hooks/customHooks.jsx
  src/hooks/useFacebookShare/index.jsx
  src/hooks/useKakaoShare/index.jsx
  src/pages/Answer/index.jsx
  src/pages/Feed/index.jsx
  src/utils/dateUtils.js
  src/utils/portal/index.jsx
  src/utils/portal/portal.jsx
  tailwind.config.js
Labels: Priority: High 🔥, Type: Merge :truck:

#60 Epic/answer 화면 구현 -> merge 브랜치 병합
  src/assets/images/icons/ic_Close.svg
  src/assets/images/icons/ic_Edit.svg
  src/assets/images/icons/ic_Rejection.svg
  src/components/AnswerContent/index.jsx
  src/components/AnswerDelete/index.jsx
  src/components/AnswerEdit/index.jsx
  src/components/AnswerEditForm/index.jsx
  src/components/AnswerRejection/index.jsx
  src/components/AnswerStatus/index.jsx
  src/components/CountFavorite/index.jsx
  src/components/DeleteIdBtn/index.jsx
  src/components/Header/index.jsx
  src/components/Kebab/index.jsx
  src/components/QnAList/index.jsx
  src/components/QuestionDelete/index.jsx
  src/pages/Answer/index.jsx
  src/pages/Home/index.jsx
Labels: Priority: High 🔥, Type: Merge :truck:

#61 Refactor/main 화면 구현
  src/assets/images/icons/ic_Arrow-dash-right.svg
  src/components/ToastHome/index.jsx
  src/pages/Home/index.jsx
Labels: Priority: Low 🐢, Type: Improve UX :arrow_up:, Type: Refactor :recycle:

#62 Refactor/feed 화면 구현
  src/components/AnswerContent/index.jsx
  src/components/CountFavorite/index.jsx
  src/components/DeleteIdBtn/index.jsx
  src/components/Header/index.jsx
  src/components/Modals/index.jsx
  src/components/ToastPostQuestion/index.jsx
  src/pages/Feed/index.jsx
  tailwind.config.js
Labels: Priority: Low 🐢, Type: Refactor :recycle:

#64 Refactor/리스트페이지 레이아웃
  src/components/ToastMovePage/index.jsx
  src/pages/QuestionList/index.jsx
Labels: Priority: Low 🐢, Type: Refactor :recycle:

#65 Epic/error 화면 구현
  src/pages/Error/index.jsx
Labels: Priority: Low 🐢, Type: Feature :sparkles:, Type: Refactor :recycle:

#66 Refactor/answer 개선
  src/components/AnswerContent/index.jsx
  src/components/AnswerDelete/index.jsx
  src/components/AnswerEdit/index.jsx
  src/components/AnswerEditForm/index.jsx
  src/components/AnswerRejection/index.jsx
  src/components/ConfirmModal/index.jsx
  src/components/DeleteIdBtn/index.jsx
  src/components/Kebab/index.jsx
  src/components/QnAList/index.jsx
  src/components/QuestionDelete/index.jsx
  src/components/ToastSuccess/index.jsx
  src/pages/Answer/index.jsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:, Type: Improve UX :arrow_up:, Type: Refactor :recycle:

#67 Refactor/all page
  src/components/AnswerEditForm/index.jsx
  src/components/App/index.jsx
  src/components/Common/AnswerContent/index.jsx
  src/components/Common/AnswerStatus/index.jsx
  src/components/Common/CountFavorite/index.jsx
  src/components/Common/CountQuestion/index.jsx
  src/components/Common/Header/index.jsx
  src/components/Common/QnAList/index.jsx
  src/components/Common/QuestionContent/index.jsx
  src/components/Context/index.jsx
  src/components/ToastSuccess/index.jsx
  src/components/UI/Kebab/AnswerDelete/index.jsx
  src/components/UI/Kebab/AnswerEdit/index.jsx
  src/components/UI/Kebab/AnswerRejection/index.jsx
  src/components/UI/Kebab/QuestionDelete/index.jsx
  src/components/UI/Kebab/index.jsx
  src/components/UI/Modals/ConfirmModal/index.jsx
  src/components/UI/Modals/index.jsx
  src/components/UI/Pagination/index.jsx
  src/components/UI/SortDropDown/index.jsx
  src/components/UI/Toast/ToastDeleteId/index.jsx
  src/components/UI/Toast/ToastHome/index.jsx
  src/components/UI/Toast/ToastMovePage/index.jsx
  src/components/UI/Toast/ToastPostQuestion/index.jsx
  src/components/UI/Toast/ToastSuccess/index.jsx
  src/config/constat.js
  src/hooks/useKakaoShare/index.jsx
  src/pages/Answer/index.jsx
  src/pages/Error/index.jsx
  src/pages/Feed/index.jsx
  src/pages/Home/index.jsx
  src/pages/Layout/index.jsx
  src/pages/QuestionList/index.jsx
  src/utils/dateUtils/index.js
  src/utils/getDynamicLimit/index.js
Labels: Priority: High 🔥, Type: Improve UX :arrow_up:, Type: Refactor :recycle:
